# Generated by Django 4.2.1 on 2023-07-27 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_parentregister_gender_parentregister_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutritions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruits', models.JSONField(blank=True, default=list)),
                ('dairy', models.JSONField(blank=True, default=list)),
                ('proteins', models.JSONField(blank=True, default=list)),
                ('cereals', models.JSONField(blank=True, default=list)),
                ('child_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.childregister')),
            ],
            options={
                'db_table': 'nutritions',
            },
        ),
    ]
