# Generated by Django 4.2.1 on 2023-07-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritions',
            name='notes',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
    ]
