# Generated by Django 4.2.1 on 2023-07-19 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('email_id', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'parent_reg',
            },
        ),
        migrations.CreateModel(
            name='ChildRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dateofbirth', models.DateField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('medical_information', models.TextField()),
                ('dieatry_preferences', models.TextField()),
                ('pickup_list', models.TextField()),
                ('parental_preferences', models.TextField()),
                ('parent_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.parentregister')),
            ],
            options={
                'db_table': 'child_reg',
            },
        ),
    ]
