# Generated by Django 4.2.1 on 2023-07-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentregister',
            name='gender',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentregister',
            name='last_name',
            field=models.CharField(default=21, max_length=20),
            preserve_default=False,
        ),
    ]
