# Generated by Django 4.2.1 on 2023-07-19 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=30)),
                ('staff_address', models.TextField()),
                ('staff_email_id', models.CharField(max_length=30)),
                ('staff_dob', models.CharField(max_length=30)),
                ('staff_gender', models.CharField(max_length=20)),
                ('staff_qualification', models.CharField(max_length=30)),
                ('staff_mobile_no', models.CharField(max_length=30)),
                ('staff_username', models.CharField(max_length=30)),
                ('staff_password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'staff_registration',
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=30)),
                ('parent_email_id', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('current_status', models.TextField()),
                ('incident_date', models.CharField(max_length=20)),
                ('parent_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.parentregister')),
            ],
            options={
                'db_table': 'incident_report',
            },
        ),
    ]
