# Generated by Django 4.2.1 on 2023-06-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=20)),
                ('parent_email_id', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('current_status', models.CharField(max_length=30)),
                ('reported_by', models.CharField(max_length=20)),
                ('incident_date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'incident_report',
            },
        ),
    ]
