# Generated by Django 4.2.1 on 2023-07-19 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_description', models.TextField()),
                ('feed_date', models.DateField()),
                ('parent_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.parentregister')),
            ],
            options={
                'db_table': 'parent_feedback',
            },
        ),
    ]
