# Generated by Django 4.2.1 on 2023-06-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_name', models.CharField(max_length=20)),
                ('feed_no', models.CharField(max_length=30)),
                ('feed_email', models.CharField(max_length=30)),
                ('feed_feedback', models.TextField()),
                ('feed_date', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'parent_feedback',
            },
        ),
    ]
