# Generated by Django 4.2.1 on 2023-06-20 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('daycare_parent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentfeedback',
            name='parent_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.parentregister'),
            preserve_default=False,
        ),
    ]
